USE INFORMATION_SCHEMA;

SET sql_mode='PIPES_AS_CONCAT';

SET @ESQUEMA = 'STAGE';
SET @TABLA ='STG_ORDERS_CRM';

SELECT 'SELECT COUNT(*) TOTAL_REGISTROS '
UNION
SELECT 
	',SUM(CASE WHEN LENGTH('||COLUMN_NAME||')!=0 THEN 1 ELSE 0 END) TOTAL_'||COLUMN_NAME||
	',COUNT(DISTINCT CASE WHEN LENGTH(TRIM('||COLUMN_NAME||'))!=0 THEN '||
		COLUMN_NAME||' ELSE 0 END) TOTAL_DISTINTOS_'||COLUMN_NAME||
	',COUNT(DISTINCT CASE WHEN LENGTH(TRIM('||COLUMN_NAME||'))!=0 THEN '||
		COLUMN_NAME||' ELSE NULL END) TOTAL_DISTINTOS_'||COLUMN_NAME
  FROM COLUMNS
 WHERE TABLE_SCHEMA =  @ESQUEMA
  AND TABLE_NAME = @TABLA  
UNION
SELECT 'FROM '|| @ESQUEMA ||'.'||@TABLA||';';


# GENERADOR DE LA CONSULTA DE REGISTROS DE TODAS LAS TABLAS DE ODS
SELECT  'SELECT '''||TABLE_NAME||''' TABLA, COUNT(*) TOTAL_REGISTROS FROM '||TABLE_NAME||' UNION ' 
FROM TABLES
 WHERE TABLE_SCHEMA = 'ODS'
  AND TABLE_NAME LIKE 'ODS_%';
  
# CONSULTA PARA SEPARAR LA DIRECCION EN CALLE Y NÚMERO  
SELECT 
	DE_DIRECCION
    ,TRIM(SUBSTRING(DE_DIRECCION FROM LENGTH(SUBSTRING_INDEX(DE_DIRECCION, ' ', 1))+1)) AS CALLE
    ,SUBSTRING_INDEX(DE_DIRECCION, ' ', 1) AS NUMERO
FROM ODS_HC_DIRECCIONES;

/*
# DE_DIRECCION, 		CALLE, NUMERO
	0 1ST ROAD,  	 1ST ROAD, 0
 0 2ND TERRACE,   2ND TERRACE, 0
	0 4TH PARK,  	 4TH PARK, 0
   0 5TH PLACE,  	5TH PLACE, 0
0 ABERG AVENUE,  ABERG AVENUE, 0
0 ABERG CIRCLE,  ABERG CIRCLE, 0
*/
