USE ODS;

/*- INSERTAMOS LOS VALORES DEL DOMINIO DE SEXOS ---------------------------*/
INSERT INTO ODS_DM_SEXOS VALUES (1, 'MALE', NOW(), NOW());
INSERT INTO ODS_DM_SEXOS VALUES (2, 'FEMALE', NOW(), NOW());
INSERT INTO ODS_DM_SEXOS VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_SEXOS VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_SEXOS;
/*--------------------------------------------------------------------------*/

/*- INSERTAMOS LOS DISTINTOS VALORES DE PROFESIONES DE STAGING -------------*/ 
INSERT INTO ODS_DM_PROFESIONES (DE_PROFESION, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(PROFESION)) PROFESION, NOW(), NOW()
FROM STAGE.stg_clientes_crm
WHERE LENGTH(TRIM(PROFESION))!=0;

COMMIT;

INSERT INTO ODS_DM_PROFESIONES VALUES (999 ,'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_PROFESIONES VALUES (998 ,'NO APLICA', NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_PROFESIONES;
/*--------------------------------------------------------------------------*/

/*- INSERTAMOS LOS DISTINTOS VALORES DE LAS COMPAÑIAS DE STAGING -----------*/
INSERT INTO ODS_DM_COMPANYAS (DE_COMPANYA, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT(UPPER(TRIM(COMPANY))) DE_COMPANYA, NOW(), NOW()
FROM STAGE.STG_CLIENTES_CRM
WHERE LENGTH(TRIM(COMPANY))!=0;

COMMIT;

INSERT INTO ODS_DM_COMPANYAS VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_COMPANYAS VALUES (998, 'NO APLICA', NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_COMPANYAS;
/*--------------------------------------------------------------------------*/

/*- INSERTAMOS LOS DISTINTOS VALORES DE PAISES DE STAGING ------------------*/
INSERT INTO ODS_DM_PAISES (DE_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT(UPPER(TRIM(COUNTRY))) DE_PAIS, NOW(), NOW()
FROM STAGE.STG_CLIENTES_CRM
WHERE LENGTH(TRIM(COUNTRY))!=0;

COMMIT;

INSERT INTO ODS_DM_PAISES VALUES (99 ,'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_PAISES VALUES (98 ,'NO APLICA', NOW(), NOW());

COMMIT;

ANALYZE TABLE ODS_DM_PAISES;
/*--------------------------------------------------------------------------*/

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

/*- INSERTAMOS LOS DISTINTOS VALORES DE CIUDADES ESTADO --------------------*/
INSERT INTO ODS_DM_CIUDADES_ESTADOS (DE_CIUDAD, DE_ESTADO, ID_PAIS, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(CLI.CITY)) DE_CIUDAD, UPPER(TRIM(CLI.STATE)) DE_ESTADO, PAI.ID_PAIS ID_PAIS, NOW() FC_INSERT, NOW() FC_MODIFICACION
  FROM STAGE.STG_CLIENTES_CRM CLI
  INNER JOIN ODS.ODS_DM_PAISES PAI ON
	CASE WHEN LENGTH(TRIM(CLI.COUNTRY))!=0 THEN
		CLI.COUNTRY
	ELSE 
		'DESCONOCIDO'
	END = PAI.DE_PAIS
WHERE LENGTH(TRIM(CLI.CITY))!=0;

COMMIT;

INSERT INTO ODS_DM_CIUDADES_ESTADOS VALUES (999, 'DESCONOCIDO', 'DESCONOCIDO', 99, NOW(), NOW());
INSERT INTO ODS_DM_CIUDADES_ESTADOS VALUES (998, 'NO APLICA', 'NO APLICA', 99, NOW(), NOW());

COMMIT;
/*--------------------------------------------------------------------------*/
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;

/*- INSERTAMOS LOS DISTINTOS VALORES DE DIRECCIONES ------------------------*/
INSERT INTO ODS_HC_DIRECCIONES (DE_DIRECCION, DE_CP, ID_CIUDAD_ESTADO, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT(UPPER(TRIM(ADDRESS))) DE_DIRECCION
	   ,CASE WHEN LENGTH(CLI.POSTAL_CODE)!=0 THEN TRIM(CLI.POSTAL_CODE) ELSE 99999 END CP
	   ,CIU.ID_CIUDAD_ESTADO ID_CIUDAD
	   ,NOW() FC_INSERT
	   ,NOW() FC_MODIFICACION
  FROM STAGE.STG_CLIENTES_CRM CLI
	INNER JOIN ODS.ODS_DM_PAISES PAI ON 
		CASE WHEN LENGTH(TRIM(CLI.COUNTRY))!=0 THEN 
			CLI.COUNTRY
		ELSE
			'DESCONOCIDO'
		END = PAI.DE_PAIS
	INNER JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON
		CASE WHEN LENGTH(TRIM(CLI.CITY))!=0 THEN
			CLI.CITY 
		ELSE 
			'DESCONOCIDO'
		END = CIU.DE_CIUDAD
		AND 
		CASE WHEN LENGTH(TRIM(CLI.STATE))!=0 THEN
			CLI.STATE
		ELSE
			'DESCONOCIDO'
		END = CIU.DE_ESTADO
 WHERE LENGTH(TRIM(ADDRESS))!=0;

COMMIT;

INSERT INTO ODS_HC_DIRECCIONES VALUES (999999, 'DESCONOCIDO', 99999, 999, NOW(), NOW());
INSERT INTO ODS_HC_DIRECCIONES VALUES (999998, 'NO APLICA', 99998, 998, NOW(), NOW());

COMMIT;
/*--------------------------------------------------------------------------*/

ANALYZE TABLE ODS_DM_PROFESIONES;
ANALYZE TABLE ODS_DM_SEXOS;
ANALYZE TABLE ODS_HC_DIRECCIONES;
ANALYZE TABLE ODS_DM_CIUDADES_ESTADO;
ANALYZE TABLE ODS_DM_COMPANYAS;
ANALYZE TABLE ODS_DM_PAISES;


/*- INSERTAMOS LOS CLIENTES SUSTITUYENDO LOS VALORES POR ID's ADECUADOS-----*/

# COJEMOS LAS DIRECCIONES QUE NO SEAN LA DE FACTURACION
CREATE TABLE TMP_DIRECCIONES_CLIENTES AS
SELECT DIR.ID_DIRECCION
	   ,DIR.DE_DIRECCION
	   ,DIR.DE_CP
	   ,CIU.DE_CIUDAD
	   ,CIU.DE_ESTADO
	   ,PAI.DE_PAIS
  FROM ODS.ODS_HC_DIRECCIONES DIR
	INNER JOIN ODS.ODS_DM_CIUDADES_ESTADOS CIU ON DIR.ID_CIUDAD_ESTADO = CIU.ID_CIUDAD_ESTADO
	INNER JOIN ODS.ODS_DM_PAISES PAI ON CIU.ID_PAIS = PAI.ID_PAIS;

ANALYZE TABLE TMP_DIRECCIONES_CLIENTES;

# ASIGNAMOS A CADA CLIENTE DE STAGE LA DIRECCION NORMALIZADA DE ODS 
CREATE TABLE TMP_DIRECCIONES_CLIENTES2 AS
SELECT CLI.CUSTOMER_ID ID_CLIENTE
	   ,DIR.ID_DIRECCION
  FROM STAGE.STG_CLIENTES_CRM CLI
	INNER JOIN ODS.TMP_DIRECCIONES_CLIENTES DIR ON
		CASE WHEN LENGTH(TRIM(ADDRESS))!=0 THEN
			UPPER(TRIM(CLI.ADDRESS))
		ELSE
			'DESCONOCIDO'
		END = DIR.DE_DIRECCION
		AND
		CASE WHEN LENGTH(TRIM(CLI.POSTAL_CODE))!=0 THEN
			TRIM(CLI.POSTAL_CODE)
		ELSE
			99999
		END = DIR.DE_CP
		AND
		CASE WHEN LENGTH(TRIM(CLI.CITY))!=0 THEN
			TRIM(CLI.CITY)
		ELSE
			'DESCONOCIDO'
		END = DIR.DE_CIUDAD
		AND
		CASE WHEN LENGTH(TRIM(CLI.STATE))!=0 THEN
			TRIM(CLI.STATE)
		ELSE
			'DESCONOCIDO'
		END = DIR.DE_ESTADO
		AND 
		CASE WHEN LENGTH(TRIM(COUNTRY))!=0 THEN
			TRIM(CLI.COUNTRY)
		ELSE
			'DESCONOCIDO'
		END = DIR.DE_PAIS;

COMMIT;

ANALYZE TABLE TMP_DIRECCIONES_CLIENTES2;

# CARGAMOS LOS CLIENTES
INSERT INTO ODS_HC_CLIENTES
SELECT CUSTOMER_ID AS ID_CLIENTE
	   ,CASE WHEN LENGTH(TRIM(FIRST_NAME))!=0 THEN TRIM(UPPER(FIRST_NAME)) ELSE 'DESCONOCIDO' END NOMBRE_CLIENTE
	   ,CASE WHEN LENGTH(TRIM(LAST_NAME))!=0 THEN TRIM(UPPER(LAST_NAME)) ELSE 'DESCONOCIDO' END APELLIDOS_CLIENTE
	   ,CASE WHEN LENGTH(TRIM(IDENTIFIED_DOC))!=0 THEN TRIM(UPPER(IDENTIFIED_DOC)) ELSE '99-999-9999' END NUMDOC_CLIENTE
	   ,SEXO.ID_SEXO
	   ,CASE WHEN LENGTH(TRIM(DIR.ID_DIRECCION))!=0 THEN DIR.ID_DIRECCION ELSE 999999 END ID_DIRECCION
	   ,CASE WHEN LENGTH(TRIM(PHONE))!=0 THEN REPLACE(PHONE,'-','') ELSE 9999999999 END TELEFONO_CLIENTE
	   ,CASE WHEN LENGTH(TRIM(EMAIL))!=0 THEN TRIM(UPPER(EMAIL)) ELSE 'DESCONOCIDO' END EMAIL
	   ,CASE WHEN LENGTH(TRIM(BIRTHDAY))!=0 THEN STR_TO_DATE(BIRTHDAY,'%d/%m/%Y') ELSE STR_TO_DATE('31/12/9999','%d/%m/%Y') END FC_NACIMIENTO
	   ,PROF.ID_PROFESION
	   ,COMP.ID_COMPANYA
	   ,NOW()
	   ,STR_TO_DATE('31/12/9999','%d/%m/%Y') 
  FROM STAGE.STG_CLIENTES_CRM CLI
	INNER JOIN ODS.ODS_DM_SEXOS SEXO ON
		CASE WHEN LENGTH(TRIM(GENDER))!=0 THEN
			UPPER(TRIM(CLI.GENDER))
		ELSE
			'DESCONOCIDO'
		END = SEXO.DE_SEXO
	INNER JOIN ODS.ODS_DM_PROFESIONES PROF ON
		CASE WHEN LENGTH(TRIM(CLI.PROFESION))!=0 THEN
			UPPER(TRIM(CLI.PROFESION))
		ELSE
			'NO APLICA'
		END = PROF.DE_PROFESION
	INNER JOIN ODS.ODS_DM_COMPANYAS COMP ON
		CASE WHEN LENGTH(TRIM(CLI.COMPANY))!=0 THEN
			UPPER(TRIM(CLI.COMPANY))
		ELSE
			'DESCONOCIDO'
		END = COMP.DE_COMPANYA
	LEFT OUTER JOIN ODS.TMP_DIRECCIONES_CLIENTES2 DIR ON DIR.ID_CLIENTE = CLI.CUSTOMER_ID;

COMMIT;

ANALYZE TABLE ODS_HC_CLIENTES;

