USE ODS;

/*- INSERTAMOS LOS VALORES DEL DOMINIO ODS_DM_METODOS_PAGO ------------------*/
INSERT INTO ODS.ODS_DM_METODOS_PAGO (DE_METODO_PAGO,FC_INSERT,FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(BILL_METHOD)) DE_METODO_PAGO, NOW(), NOW()
FROM STAGE.STG_FACTURAS_FCT
WHERE LENGTH(TRIM(BILL_METHOD))!=0;

COMMIT;

ANALYZE TABLE ODS_DM_METODOS_PAGO;
/*---------------------------------------------------------------------------*/

/*- INSERTAMOS LOS VALORES DEL DOMINIO ODS_DM_CICLOS_FACTURACION -----------------------*/
INSERT INTO ODS.ODS_DM_CICLOS_FACTURACION (DE_CICLO_FACTURACION,FC_INSERT,FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(BILL_CYCLE)) DE_CICLO_FACTURACION, NOW(), NOW()
FROM STAGE.STG_FACTURAS_FCT
WHERE LENGTH(TRIM(BILL_CYCLE))!=0;

COMMIT;

ANALYZE TABLE ODS_DM_CICLOS_FACTURACION;
/*---------------------------------------------------------------------------------------*/



SELECT FCT.BILL_REF_NO, CLI.ID_CLIENTE
FROM STAGE.STG_FACTURAS_FCT FCT
INNER JOIN ODS.ods_hc_clientes CLI ON FCT.CUSTOMER_ID = CLI.ID_CLIENTE;
/*371160
420000 - 371160 = 48840 QUE NO TENEMOS EL CLIENTE
*/

INSERT INTO ODS.ODS_HC_FACTURAS (ID_FACTURA, ID_CLIENTE, ID_CICLO_FACTURACION,
								 ID_METODO_PAGO, CANTIDAD, FC_INICIO, FC_FIN,
                                 FC_FACTURACION, FC_PAGO, FC_INSERT, FC_MODIFICACION)
SELECT FCT.BILL_REF_NO    					 AS ID_FACTURA
	   ,CLI.ID_CLIENTE						 AS ID_CLIENTE
       ,CIFA.ID_CICLO_FACTURACION 			 AS ID_CICLO_FACTURACION
       ,PAG.ID_METODO_PAGO					 AS ID_METODO_PAGO
       ,FCT.AMOUNT 							 AS CANTIDAD
       ,FCT.START_DATE 						 AS FC_INICIO
       ,FCT.END_DATE 						 AS FC_FIN
       ,FCT.STATEMENT_DATE 					 AS FC_FACTURACION
       ,FCT.PAYMENT_DATE			 		 AS FC_PAGO
       ,NOW() 								 AS FC_INSERT
       ,STR_TO_DATE('31/12/9999','%d/%m/%Y') AS FC_MODIFICACION
  FROM STAGE.STG_FACTURAS_FCT FCT
	INNER JOIN ODS.ODS_DM_METODOS_PAGO PAG ON UPPER(FCT.BILL_METHOD) = PAG.DE_METODO_PAGO
	INNER JOIN ODS.ODS_DM_CICLOS_FACTURACION CIFA ON UPPER(FCT.BILL_CYCLE) = CIFA.DE_CICLO_FACTURACION
	LEFT OUTER JOIN ODS.ODS_HC_CLIENTES CLI ON FCT.CUSTOMER_ID = CLI.ID_CLIENTE;
/*420000 FACTURAS INSERTADAS*/

COMMIT;

ANALYZE TABLE ODS_HC_FACTURAS;

