USE ODS;

CREATE TABLE IF NOT EXISTS ODS.ODS_HC_SERVICIOS(
	ID_SERVICIO INT UNSIGNED NOT NULL PRIMARY KEY
	,ID_CLIENTE INT(11)
	,ID_PRODUCTO INT(10)
	,ID_CANAL INT(10)
	,ID_AGENTE INT(11)
	,ID_DIRECCION_SERVICIO INT(10)
	,PUNTO_ACESO VARCHAR(512)
	,FC_INICIO DATETIME 
	,FC_INSTALACION DATETIME 
	,FC_FIN DATETIME 
	,FC_INSERT DATETIME 
	,FC_MODIFICACION DATETIME 
);

CREATE TABLE IF NOT EXISTS ODS.ODS_DM_PRODUCTOS(
	ID_PRODUCTO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY 
	,DE_PRODUCTO VARCHAR(512)
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);

CREATE TABLE IF NOT EXISTS ODS.ODS_DM_CANALES(
	ID_CANAL INT UNSIGNED AUTO_INCREMENT PRIMARY KEY 
	,DE_CANAL VARCHAR(512)
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);

/*----- AÑADIMOS LAS RELACIONES --------------------------------*/
# RELACION DE LA TABLA SERVICIOS CON LA TABLA CLIENTES
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_cli FOREIGN KEY (ID_CLIENTE)
	REFERENCES ODS.ODS_HC_CLIENTES (ID_CLIENTE)
	ON DELETE NO ACTION ON UPDATE NO ACTION;

# RELACION DE LA TABLA SERVICIOS CON LA TABLA PRODUCTOS
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_pro_idx (ID_PRODUCTO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS MODIFY COLUMN ID_PRODUCTO INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_pro FOREIGN KEY (ID_PRODUCTO)
	REFERENCES ODS.ODS_DM_PRODUCTOS (ID_PRODUCTO)
	ON DELETE NO ACTION ON UPDATE NO ACTION;

# RELACION DE LA TABLA SERVICIOS CON LA TABLA CANALES
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_canal_idx (ID_CANAL ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS MODIFY COLUMN ID_CANAL INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_canal FOREIGN KEY (ID_CANAL)
	REFERENCES ODS.ODS_DM_CANALES (ID_CANAL)
	ON DELETE NO ACTION ON UPDATE NO ACTION;

# RELACION DE LA TABLA SERVICIOS CON LA TABLA DIRECCIONES
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_dir_idx (ID_DIRECCION_SERVICIO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS MODIFY COLUMN ID_DIRECCION_SERVICIO INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_ser_dir FOREIGN KEY (ID_DIRECCION_SERVICIO)
	REFERENCES ODS.ODS_HC_DIRECCIONES (ID_DIRECCION)
	ON DELETE NO ACTION ON UPDATE NO ACTION;