USE ODS;

CREATE TABLE IF NOT EXISTS ODS.ODS_HC_PEDIDOS(
	ID_PEDIDO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	,ID_OP_GRUPO_PEDIDO INT(10) UNSIGNED
    ,ID_SERVICIO INT(10) UNSIGNED
	,ID_ETAPA INT(10) UNSIGNED
	,ID_AGENTE INT(10) UNSIGNED	
	,FC_INICIO DATETIME 
	,FC_FIN DATETIME 
	,FC_INSERT DATETIME 
	,FC_MODIFICACION DATETIME 
);

CREATE TABLE IF NOT EXISTS ODS.ODS_DM_ETAPAS(
	ID_ETAPA INT UNSIGNED AUTO_INCREMENT PRIMARY KEY 
	,DE_ETAPA VARCHAR(512)
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);


/*----- AÑADIMOS LAS RELACIONES --------------------------------*/
# RELACION DE LA TABLA PEDIDOS CON LA TABLA ETAPAS
ALTER TABLE ODS.ODS_HC_PEDIDOS ADD INDEX fk_ped_eta_idx (ID_ETAPA ASC);
ALTER TABLE ODS.ODS_HC_PEDIDOS ADD CONSTRAINT fk_ped_eta FOREIGN KEY (ID_ETAPA)
	REFERENCES ODS.ODS_DM_ETAPAS (ID_ETAPA)
	ON DELETE NO ACTION ON UPDATE NO ACTION;

# RELACION DE LA TABLA PEDIDOS CON LA TABLA AGENTES
ALTER TABLE ODS.ODS_HC_PEDIDOS ADD INDEX fk_ser_pro_idx (ID_AGENTE ASC);
ALTER TABLE ODS.ODS_HC_PEDIDOS ADD CONSTRAINT fk_ped_age FOREIGN KEY (ID_AGENTE)
	REFERENCES ODS.ODS_DM_AGENTES (ID_AGENTE)
	ON DELETE NO ACTION ON UPDATE NO ACTION;
    
# RELACION DE LA TABLA PEDIDOS CON LA TABLA SERVICIOS
# CREAMOS EL CAMPO ID_PEDIDO EN ODS_HC_SERVICIOS PARA HACER LA RELACIÓN CON ESTE
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD COLUMN `ID_PEDIDO` INT(10) UNSIGNED NULL AFTER `ID_DIRECCION_SERVICIO`;

ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_ser_ped_idx (ID_PEDIDO ASC);
    
ALTER TABLE ODS.ODS_HC_PEDIDOS ADD CONSTRAINT fk_ped_ser FOREIGN KEY (ID_PEDIDO)
	REFERENCES ODS.ODS_HC_SERVICIOS (ID_PEDIDO)
	ON DELETE NO ACTION ON UPDATE NO ACTION;      
