USE ODS;

DROP TABLE IF EXISTS ODS_DM_DEPARTAMENTOS;

CREATE TABLE ODS_DM_DEPARTAMENTOS (
	ID_DEPARTAMENTO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
    ,DE_DEPARTAMENTO VARCHAR(512)
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);


DROP TABLE IF EXISTS ODS_DM_AGENTES;

CREATE TABLE ODS_DM_AGENTES (
	ID_AGENTE INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
    ,DE_AGENTE VARCHAR(512)
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_HC_LLAMADAS;

CREATE TABLE ODS_HC_LLAMADAS (
	ID_LLAMADA INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
    ,ID_OP_LLAMADA INT             # MANTENEMOS EL ID DEL OPERACIONAL PARA NO PERDER LA TRAZA CON ESTE
    ,ID_CLIENTE INT 
    ,ID_DEPARTAMENTO INT UNSIGNED
    ,ID_AGENTE INT UNSIGNED
    ,TELEFONO_LLAMADA BIGINT(20)
    ,FLG_TRANSFERIDO TINYINT(1)
    ,FC_INICIO_LLAMADA DATETIME
    ,FC_FIN_LLAMADA DATETIME
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);

/*----- AÑADIMOS LAS RELACIONES --------------------------------*/

# RELACION DE LA TABLA ODS_HC_LLAMADAS CON LA TABLA ODS_HC_CLIENTES
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX fk_call_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT fk_call_cli FOREIGN KEY (ID_CLIENTE)
	REFERENCES ODS.ODS_HC_CLIENTES (ID_CLIENTE);

# RELACION DE LA TABLA ODS_HC_LLAMADAS CON LA TABLA ODS_DM_DEPARTAMENTOS  
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX fk_call_dep_idx (ID_DEPARTAMENTO ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT fk_call_dep FOREIGN KEY (ID_DEPARTAMENTO)
	REFERENCES ODS.ODS_DM_DEPARTAMENTOS (ID_DEPARTAMENTO);
    
# RELACION DE LA TABLA ODS_HC_LLAMADAS CON LA TABLA ODS_DM_AGENTES  
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD INDEX fk_call_age_idx (ID_AGENTE ASC);
ALTER TABLE ODS.ODS_HC_LLAMADAS ADD CONSTRAINT fk_call_age FOREIGN KEY (ID_AGENTE)
	REFERENCES ODS.ODS_DM_AGENTES (ID_AGENTE);    