USE ODS;

DROP TABLE IF EXISTS ODS_HC_CLIENTES;

CREATE TABLE ODS_HC_CLIENTES(
	ID_CLIENTE INT NOT NULL PRIMARY KEY
	,NOMBRE_CLIENTE VARCHAR(512)
	,APELLIDOS_CLIENTE VARCHAR(512)
	,NUMDOC_CLIENTE VARCHAR(24)
	,ID_SEXO INT
	,ID_DIRECCION_CLIENTE INT 
	,TELEFONO_CLIENTE BIGINT
	,EMAIL VARCHAR(512)
	,FC_NACIMIENTO DATE
	,ID_PROFESION INT
	,ID_COMPANYA INT
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_SEXOS;
CREATE TABLE ODS_DM_SEXOS(
	 ID_SEXO INT UNSIGNED NOT NULL PRIMARY KEY 
	,DE_SEXO VARCHAR(64)
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_PROFESIONES;
CREATE TABLE ODS_DM_PROFESIONES(
	ID_PROFESION  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY 
	,DE_PROFESION VARCHAR(512)
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_COMPANYAS;
CREATE TABLE ODS_DM_COMPANYAS(
	ID_COMPANYA INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
	,DE_COMPANYA VARCHAR(512)
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_HC_DIRECCIONES;
CREATE TABLE ODS_HC_DIRECCIONES(
	ID_DIRECCION INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
	,DE_DIRECCION VARCHAR(512)
	,DE_CP INT
	,ID_CIUDAD_ESTADO INT
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);	

DROP TABLE IF EXISTS ODS_DM_CIUDADES_ESTADOS;
CREATE TABLE ODS_DM_CIUDADES_ESTADOS(
	ID_CIUDAD_ESTADO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
	,DE_CIUDAD VARCHAR(512)
	,DE_ESTADO VARCHAR(512)
	,ID_PAIS INT
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);

DROP TABLE IF EXISTS ODS_DM_PAISES;
CREATE TABLE ODS_DM_PAISES(
	ID_PAIS INT UNSIGNED AUTO_INCREMENT PRIMARY KEY
	,DE_PAIS VARCHAR(512)
	,FC_INSERT DATETIME
	,FC_MODIFICACION DATETIME
);

/*----- AÑADIMOS LAS RELACIONES --------------------------------*/
# RELACION DE LA TABLA CLIENTES CON LA TABLA SEXOS
ALTER TABLE ODS.ODS_HC_CLIENTES MODIFY COLUMN ID_SEXO INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_CLIENTES ADD INDEX fk_cli_sexo_idx (ID_SEXO ASC);
ALTER TABLE ODS.ODS_HC_CLIENTES ADD CONSTRAINT fk_cli_sexo FOREIGN KEY (ID_SEXO)
	REFERENCES ODS.ODS_DM_SEXOS (ID_SEXO);

# RELACION DE LA TABLA CLIENTES CON LA TABLA PROFESIONES
ALTER TABLE ODS.ODS_HC_CLIENTES MODIFY COLUMN ID_PROFESION INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_CLIENTES ADD INDEX fk_cli_prof_idx (ID_PROFESION ASC);
ALTER TABLE ODS.ODS_HC_CLIENTES ADD CONSTRAINT fk_cli_prof FOREIGN KEY (ID_PROFESION)
	REFERENCES ODS.ODS_DM_PROFESIONES (ID_PROFESION);

# RELACION DE LA TABLA CLIENTES CON LA TABLA COMPANYAS
ALTER TABLE ODS.ODS_HC_CLIENTES MODIFY COLUMN ID_COMPANYA INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_CLIENTES ADD INDEX fk_cli_comp_idx (ID_COMPANYA ASC);
ALTER TABLE ODS.ODS_HC_CLIENTES ADD CONSTRAINT fk_cli_comp FOREIGN KEY (ID_COMPANYA)
	REFERENCES ODS.ODS_DM_COMPANYAS (ID_COMPANYA);

# RELACION DE LA TABLA CLIENTES CON LA TABLA DIRECCIONES
ALTER TABLE ODS.ODS_HC_CLIENTES MODIFY COLUMN ID_DIRECCION_CLIENTE INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_CLIENTES ADD INDEX fk_cli_dir_idx (ID_DIRECCION_CLIENTE ASC);
ALTER TABLE ODS.ODS_HC_CLIENTES ADD CONSTRAINT fk_cli_dir FOREIGN KEY (ID_DIRECCION_CLIENTE)
	REFERENCES ODS.ODS_HC_DIRECCIONES (ID_DIRECCION);

# RELACION DE LA TABLA CIUDADES_ESTADO CON PAISES
ALTER TABLE ODS.ODS_DM_CIUDADES_ESTADOS MODIFY COLUMN ID_PAIS INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_DM_CIUDADES_ESTADOS ADD INDEX fk_ciu_pai_idx (ID_PAIS ASC);
ALTER TABLE ODS.ODS_DM_CIUDADES_ESTADOS ADD CONSTRAINT fk_cli_pai FOREIGN KEY (ID_PAIS)
	REFERENCES ODS.ODS_DM_PAISES (ID_PAIS);

# RELACION DE LA TABLA CIUDADES_ESTADO CON DIRECCIONES
ALTER TABLE ODS.ODS_HC_DIRECCIONES MODIFY COLUMN ID_CIUDAD_ESTADO INT(10) UNSIGNED;
ALTER TABLE ODS.ODS_HC_DIRECCIONES ADD INDEX fk_dir_ciu_idx (ID_CIUDAD_ESTADO ASC);
ALTER TABLE ODS.ODS_DM_CIUDADES_ESTADOS ADD CONSTRAINT fk_dir_ciu FOREIGN KEY (ID_CIUDAD_ESTADO)
	REFERENCES ODS.ODS_HC_DIRECCIONES (ID_CIUDAD_ESTADO);

