USE STAGE;

/* HECHAMOS UN VISTAZO AL CONTINEDO DE LA TABLA */
SELECT *
FROM STAGE.STG_PRODUCTOS_CRM;

/* HACEMOS UN RECUENTO DE REGISTROS TOTALES Y DISTINTOS */
SELECT COUNT(*) TOTAL_REGISTROS
	,SUM(CASE WHEN LENGTH(PRODUCT_ID)!=0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_ID
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PRODUCT_ID))!=0 THEN PRODUCT_ID ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_ID
	,SUM(CASE WHEN LENGTH(CUSTOMER_ID)!=0 THEN 1 ELSE 0 END) TOTAL_CUSTOMER_ID
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(CUSTOMER_ID))!=0 THEN CUSTOMER_ID ELSE 0 END) TOTAL_DISTINTOS_CUSTOMER_ID
	,SUM(CASE WHEN LENGTH(PRODUCT_NAME)!=0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_NAME
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PRODUCT_NAME))!=0 THEN PRODUCT_NAME ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_NAME
	,SUM(CASE WHEN LENGTH(ACCESS_POINT)!=0 THEN 1 ELSE 0 END) TOTAL_ACCESS_POINT
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(ACCESS_POINT))!=0 THEN ACCESS_POINT ELSE 0 END) TOTAL_DISTINTOS_ACCESS_POINT
	,SUM(CASE WHEN LENGTH(CHANNEL)!=0 THEN 1 ELSE 0 END) TOTAL_CHANNEL
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(CHANNEL))!=0 THEN CHANNEL ELSE 0 END) TOTAL_DISTINTOS_CHANNEL
	,SUM(CASE WHEN LENGTH(AGENT_CODE)!=0 THEN 1 ELSE 0 END) TOTAL_AGENT_CODE
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(AGENT_CODE))!=0 THEN AGENT_CODE ELSE 0 END) TOTAL_DISTINTOS_AGENT_CODE
	,SUM(CASE WHEN LENGTH(START_DATE)!=0 THEN 1 ELSE 0 END) TOTAL_START_DATE
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(START_DATE))!=0 THEN START_DATE ELSE 0 END) TOTAL_DISTINTOS_START_DATE
	,SUM(CASE WHEN LENGTH(INSTALL_DATE)!=0 THEN 1 ELSE 0 END) TOTAL_INSTALL_DATE
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(INSTALL_DATE))!=0 THEN INSTALL_DATE ELSE 0 END) TOTAL_DISTINTOS_INSTALL_DATE
	,SUM(CASE WHEN LENGTH(END_DATE)!=0 THEN 1 ELSE 0 END) TOTAL_END_DATE
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(END_DATE))!=0 THEN END_DATE ELSE 0 END) TOTAL_DISTINTOS_END_DATE
	,SUM(CASE WHEN LENGTH(PRODUCT_CITY)!=0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_CITY
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PRODUCT_CITY))!=0 THEN PRODUCT_CITY ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_CITY
	,SUM(CASE WHEN LENGTH(PRODUCT_ADDRESS)!=0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_ADDRESS
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PRODUCT_ADDRESS))!=0 THEN PRODUCT_ADDRESS ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_ADDRESS
	,SUM(CASE WHEN LENGTH(PRODUCT_POSTAL_CODE)!=0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_POSTAL_CODE
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PRODUCT_POSTAL_CODE))!=0 THEN PRODUCT_POSTAL_CODE ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_POSTAL_CODE
	,SUM(CASE WHEN LENGTH(PRODUCT_STATE)!=0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_STATE
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PRODUCT_STATE))!=0 THEN PRODUCT_STATE ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_STATE
	,SUM(CASE WHEN LENGTH(PRODUCT_COUNTRY)!=0 THEN 1 ELSE 0 END) TOTAL_PRODUCT_COUNTRY
	,COUNT(DISTINCT CASE WHEN LENGTH(TRIM(PRODUCT_COUNTRY))!=0 THEN PRODUCT_COUNTRY ELSE 0 END) TOTAL_DISTINTOS_PRODUCT_COUNTRY
 FROM STAGE.STG_PRODUCTOS_CRM;

/*-------------------------- PRODUCT_ID --------------------------------*/

# MIRMOS SI HAY ALGUNO QUE NO PODAMOS PASARLO A NUMERO POSITIVO
SELECT DISTINCT REPLACE(PRODUCT_ID,' ','') AS REFERENCIAS_MAL_FOMADOS
FROM STAGE.STG_PRODUCTOS_CRM
WHERE REPLACE(PRODUCT_ID,' ','') NOT REGEXP '^(\\+){0,1}([0-9]+)$'
  AND LENGTH(TRIM(PRODUCT_ID)) != 0;
  
# NO DEVUELVE NADA, CON LO QUE NO TENEMOS REFERENCIAS MAL FORMADAS
  
/*-----------------------------------------------------------------------*/

/*-------------------------- CUSTOMER_ID --------------------------------*/
# MIRMOS SI HAY ALGUNO QUE NO PODAMOS PASARLO A NUMERO POSITIVO
SELECT DISTINCT REPLACE(CUSTOMER_ID,' ','') AS REFERENCIAS_MAL_FOMADOS
FROM STAGE.STG_PRODUCTOS_CRM
WHERE REPLACE(CUSTOMER_ID,' ','') NOT REGEXP '^(\\+){0,1}([0-9]+)$'
  AND LENGTH(TRIM(CUSTOMER_ID)) != 0;
/*-----------------------------------------------------------------------*/
  
/*-------------------------- PRODUCT_NAME --------------------------------*/
SELECT PRODUCT_NAME, COUNT(*)
FROM STAGE.STG_PRODUCTOS_CRM
GROUP BY PRODUCT_NAME;
/*
# 	  		  PRODUCT_NAME, COUNT(*)
	 Electric Vehicle Base, 3652
Net Energy Metering Add-on, 7433
				SmartRate, 11331
			 Solar Choice, 11025
			  Tiered Rate, 22644
			  Time-of-Use, 22410


TODAS LOS PRODUCTOS TIENEN NOMBRE, 
PERO SOLO HAY 6 NOMBRES DE PRODUCTO DISTINTOS POR LO QUE 
SE CREARÁ EL DOMINIO ODS_DM_PRODUCTOS
*/
/*-----------------------------------------------------------------------*/  

/*-------------------------- ACCESS_POINT --------------------------------*/
/*
EN LA PRIMERA CONSULTA YA SE HA VISTO QUE TODOS LOS ACCESS_POINT SON DISTINTOS
EXCEPTO LOS 221 NULOS. NO SE REALIZARÁ NIGUNA ACCION CON ESTE CAMPO Y SE PASARÁ 
A ODS TAL CUAL
*/
/*-----------------------------------------------------------------------*/  

/*-------------------------- CHANNEL --------------------------------*/
# VEMOS LAS REPETICIONES DE CADA AGENTE
SELECT TRIM(CHANNEL) CANAL, COUNT(*)
FROM STAGE.STG_PRODUCTOS_CRM
GROUP BY TRIM(CHANNEL)
ORDER BY 2 DESC;
/*
# 	 CANAL, COUNT(*)
	Online, 28537
	Retail, 21393
Callcenter, 21237
	   App, 7107
		  , 221
          
CASI TODOS LOS PRODUCTOS TIENEN EL CANAL, 
PERO SOLO HAY CUATRO CANALES DISTINTOS POR LO QUE 
SE CREARÁ EL DOMINIO ODS_DM_CANALES          
*/
/*-----------------------------------------------------------------------*/

/*-------------------------- AGENT_CODE --------------------------------*/
# VEMOS LAS REPETICIONES DE CADA AGENTE
SELECT TRIM(AGENT_CODE) AGENTE, COUNT(*)
FROM STAGE.STG_PRODUCTOS_CRM
GROUP BY TRIM(AGENT_CODE)
ORDER BY 2 DESC;
/*
# AGENTE, COUNT(*)
		, 35865
	 237, 135
	 169, 135
	 256, 130
	 114, 130
	 266, 129
	 155, 129
	 227, 129
...
*/
/*-----------------------------------------------------------------------*/

/*-------------------------- START_DATE --------------------------------*/
SELECT LENGTH(TRIM(START_DATE)), COUNT(*)
FROM STAGE.STG_PRODUCTOS_CRM
GROUP BY LENGTH(TRIM(START_DATE));
/*
10, 78495
SEGURAMENTE SOLO HAY UN FORMATO DE FECHA
*/


SELECT START_DATE
FROM STAGE.STG_PRODUCTOS_CRM
WHERE LENGTH(TRIM(START_DATE)) = 10;
/*
# START_DATE

19/04/2006
25/05/2007
26/08/2004
06/01/2016
...
*/

# COMPROBEMOS EL FORMATO PARA PODER PASARLO A DATETIME
SELECT START_DATE 
FROM STAGE.STG_PRODUCTOS_CRM
WHERE START_DATE NOT RLIKE '^([0-3][0-9])/([0-1][0-9])/([0-9]{2,4})(( [0-2][0-9]):([0-5][0-9]):([0-5][0-9])){0,1}$'
  AND LENGTH(TRIM(START_DATE))!=0;
# NO DEVUELVE NADA, POR TANTO TODOS CUMPLEN EL FORMATO

/*-----------------------------------------------------------------------*/

/*-------------------------- INSTALL_DATE --------------------------------*/
SELECT LENGTH(TRIM(INSTALL_DATE)), COUNT(*)
FROM STAGE.STG_PRODUCTOS_CRM
GROUP BY LENGTH(TRIM(INSTALL_DATE));
/*
0, 3132
23, 75363
SEGURAMENTE SOLO HAY UN FORMATO DE FECHA
*/


SELECT INSTALL_DATE
FROM STAGE.STG_PRODUCTOS_CRM
WHERE LENGTH(TRIM(INSTALL_DATE)) = 23;
/*
# INSTALL_DATE
2006-05-02 22:47:41 UTC
2007-06-11 17:03:01 UTC
2004-09-08 06:56:33 UTC
2016-01-11 18:04:55 UTC
2010-10-15 02:41:18 UTC
1998-07-27 10:51:22 UTC
2004-11-14 18:34:13 UTC
2005-04-28 23:47:30 UTC
...
*/

# COMPROBEMOS EL FORMATO PARA PODER PASARLO A DATETIME
SELECT INSTALL_DATE 
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(INSTALL_DATE) NOT RLIKE '^([0-9]{2,4})-([0-1][0-9])-([0-3][0-9])(( [0-2][0-9]):([0-5][0-9]):([0-5][0-9]) UTC){0,1}$'
  AND LENGTH(TRIM(INSTALL_DATE))!=0;
# NO DEVUELVE NADA, POR TANTO TODOS CUMPLEN EL FORMATO

/*-----------------------------------------------------------------------*/

/*-------------------------- END_DATE --------------------------------*/
SELECT LENGTH(TRIM(END_DATE)), COUNT(*)
FROM STAGE.STG_PRODUCTOS_CRM
GROUP BY LENGTH(TRIM(END_DATE));
/*
0, 31811
23, 46684

SEGURAMENTE SOLO HAY UN FORMATO DE FECHA
*/


SELECT END_DATE
FROM STAGE.STG_PRODUCTOS_CRM
WHERE LENGTH(TRIM(END_DATE)) = 23;
/*
# END_DATE
2006-09-16 22:47:41 UTC
2010-02-09 17:03:01 UTC
2017-12-19 18:04:55 UTC
2010-12-18 02:41:18 UTC
1999-03-17 10:51:22 UTC
2006-09-19 18:34:13 UTC
2013-12-21 21:06:03 UTC
...
*/

# COMPROBEMOS EL FORMATO PARA PODER PASARLO A DATETIME
SELECT END_DATE 
FROM STAGE.STG_PRODUCTOS_CRM
WHERE TRIM(END_DATE) NOT RLIKE  '^([0-9]{2,4})-([0-1][0-9])-([0-3][0-9])(( [0-2][0-9]):([0-5][0-9]):([0-5][0-9]) UTC){0,1}$'
  AND LENGTH(TRIM(END_DATE))!=0;
# NO DEVUELVE NADA, POR TANTO TODOS CUMPLEN EL FORMATO

/*-----------------------------------------------------------------------*/


/*-------------------------- PRODUCT_CITY --------------------------------*/
SELECT PRODUCT_CITY, COUNT(*)
FROM STAGE.STG_PRODUCTOS_CRM
GROUP BY PRODUCT_CITY;
/*
#	PRODUCT_CITY, COUNT(*)
		 	   , 221
	   Alhambra, 326
  	    Anaheim, 875
Apache Junction, 291
	Bakersfield, 1415
	   Berkeley, 551
		   Brea, 282
	    Burbank, 560
...

CASI TODOS LOS PRODUCTOS TIENEN CIUDAD
*/
/*-----------------------------------------------------------------------*/  

/*-------------------------- PRODUCT_ADDRESS --------------------------------*/
SELECT PRODUCT_ADDRESS, COUNT(*)
FROM STAGE.STG_PRODUCTOS_CRM
GROUP BY PRODUCT_ADDRESS
ORDER BY 2 DESC;
/*
# 		  PRODUCT_ADDRESS, COUNT(*)
						 , 221
	    0 Clarendon Plaza, 4
	7 International Alley, 4
			  9 Toban Way, 4
		  9 Carioca Drive, 3
			9 Center Pass, 3
	9 International Place, 3
		9 Vahlen Junction, 3

...

CASI TODOS LOS PRODUCTOS TIENEN DIRECCION Y POCAS SE REPITEN
*/
/*-----------------------------------------------------------------------*/  

/*-------------------------- PRODUCT_POSTAL_CODE --------------------------------*/
SELECT PRODUCT_POSTAL_CODE, COUNT(*)
FROM STAGE.STG_PRODUCTOS_CRM
GROUP BY PRODUCT_POSTAL_CODE
ORDER BY 2 DESC;
/*
# PRODUCT_POSTAL_CODE, COUNT(*)
				95397, 338
				94544, 329
				91841, 326
				92405, 325
				95054, 325
				92191, 323
				92717, 320
...

CASI TODOS LOS PRODUCTOS TIENEN CP Y LOGICAMENTE SE REPITEN MAS
QUE LA DIRECCIÓN
*/
/*-----------------------------------------------------------------------*/  

/*-------------------------- PRODUCT_STATE --------------------------------*/
SELECT PRODUCT_STATE, COUNT(*)
FROM STAGE.STG_PRODUCTOS_CRM
GROUP BY PRODUCT_STATE
ORDER BY 2 DESC;
/*
# PRODUCT_STATE, COUNT(*)
	 California, 59053
		Arizona, 11362
		 Nevada, 7675
			   , 405

CASI TODOS LOS PRODUCTOS TIENEN ESTADO Y SOLO HAY 3 DISTINTOS
*/
/*-----------------------------------------------------------------------*/  

/*-------------------------- PRODUCT_COUNTRY --------------------------------*/
SELECT PRODUCT_COUNTRY, COUNT(*)
FROM STAGE.STG_PRODUCTOS_CRM
GROUP BY PRODUCT_COUNTRY
ORDER BY 2 DESC;
/*
# PRODUCT_COUNTRY, COUNT(*)
	United States, 78274
				 , 221

CASI TODOS LOS PRODUCTOS TIENEN PAIS Y SOLO HAY UNO DISTINTO
*/
/*-----------------------------------------------------------------------*/  